title: Smit Topiwala # your name (or website title) here
logo: "/images/logo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
 •Currently pursuing MS in Data Science at the University of Alabama at Birmingham.<br>
 •I am passionate about building impactful data products and learning the best coding practices for data science.<br>
 •Solid background in Python programming, statistics, and machine learning algorithms.<br>
 •Interested in data science/analytics opportunities.<br> 
 
  <a href="https://www.linkedin.com/in/smit-topiwala-93336412b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
