title: Smit Topiwala # your name (or website title) here
logo: "/images/logo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
•Currently pursuing MS in Data Science at the University of Alabama at Birmingham, expect to graduate in 2021.
•Experienced in data manipulation, predictive modeling, data wrangling, and building dashboards.
•I am passionate about building impactful data products and learning the best coding practices for data science.
•Solid background in Python programming, statistics, and machine learning algorithms.
•Interested in data science/analytics opportunities. 
  <br><br>
  <a href="https://www.linkedin.com/in/smit-topiwala-93336412b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
